### ISSUE TITLE
Download season subtitles

### ISSUE THREAD

**Issue by deklica** [tturkalj/service.subtitles.titlovi-com-official#5]
Hvala na Matrix verziji...
Da li bi mogao, da doradis skriptu, posto za serije trazi po epizodi, na pr. S01E05, za dosta serija su titlovi postavljeni po sezonama, kao zip fajl sa svim titlovima iz sezone, i nema individualno po epizodi, pa onda i sam titl ne nalazi. Dakle posto nema informaciju o epizodi, da pored egzaktnog trazenja kao u primeru, izbaci rezultate i za titlove gde nema informacije o epizodi a sezona se uklapa, dakle u primeru S01.
Na primer Bimilui Soop S01E10, na pretrazi ne nalazi titl, ali ukoliko bi gledao i sezonske titlove pronasao bi Bimilui Soop S01.

Pozdrav i nadam se da ce se nova verzija skoro naci na zvanicnom repository-ju

English ;)
Could you refine the script, since the series is searched by episode, e.g. S01E05, for a lot of series the subtitles are set by seasons, as a zip file with all the subtitles from the season, and there is no individual by episode, so then the subtitle itself is not found. So since there is no information about the episode, in addition to the exact search as in the example, it also outputs results for subtitles where there is no information about the episode and the season fits, so in the example S01.
For example, Bimilui Soop S01E10, does not search subtitles, but if you look at seasonal subtitles, you would find Bimilui Soop S01.

**Comment by tturkalj** [comment]
Makes sense, I will look into it. 

Also, Matrix update is not yet published to the official addon repository. I will try to finish that in the following days.

**Comment by deklica** [comment]
Ima li nade za ovaj moj predlog? ;)

**Comment by xalexas** [comment]
i'm using Kodi on Android TV box. Titlovi Kodi addon throws an error when trying to download a season in a zip file. For example, I tried to download subtitles for "Physical", since there is no other subtitles in search result but only zip files, addon throws an error.

Excerpt from log file:

2021-11-27 00:00:54.587 T:12853   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: function missing required argument 'message' (pos 2)
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/service.subtitles.titlovi-com-official/service.py", line 586, in <module>
                                                       action_handler.handle_action()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/service.subtitles.titlovi-com-official/service.py", line 329, in handle_action
                                                       self.handle_search_action()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/service.subtitles.titlovi-com-official/service.py", line 467, in handle_search_action
                                                       show_notification(get_string(32001))
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/service.subtitles.titlovi-com-official/service.py", line 100, in show_notification
                                                       xbmcgui.Dialog().notification(message)
                                                   TypeError: function missing required argument 'message' (pos 2)
                                                   -->End of Python script error report<--
                                                   
2021-11-27 00:00:55.171 T:12853    INFO <general>: Python interpreter stopped
2021-11-27 00:00:55.178 T:12812   ERROR <general>: GetDirectory - Error getting plugin://service.subtitles.titlovi-com-official/?action=search&languages=Bosnian%2cCroatian%2cEnglish%2cSerbian&preferredlanguage=Serbian
2021-11-27 00:00:58.685 T:12718    INFO <general>: Loading skin file: DialogKeyboard.xml, load type: KEEP_IN_MEMORY
